[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "qupkake"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0",
    "torch-geometric>=2.3",
    "pytorch-lightning>=2.0.2",
    "torchmetrics",
    "numpy>=1.25",
    "pandas>=2.1",
    "rdkit>=2022.03.3",
    "scipy>=1.11",
]
description = "Predict micro-pKa of organic molecules"
readme = "README.md"
authors = [{ name = "Omri D Abarbanel", email = "oda6@pitt.edu" },]
license ="BSD-3-Clause"
classifiers = ["Programming Language :: Python :: 3"]

[project.urls]
"Source" = "https://github.com/shualdon/qupkake/"
"Documentation" = "https://qupkake.readthedocs.io/"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"qupkake"  = ["models/*.ckpt", "xtb/bin/*", "smirks/*.txt"]

[tool.setuptools.dynamic]
version = {attr = "qupkake.__version__"}

[project.scripts]
qupkake = "qupkake.cli:main"